# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'ESMegrationDemo' do
  use_frameworks!
  pod "ESMigration", :path => '../'

end

target 'ESMigrationDemo_macos' do
  use_frameworks!
  pod "ESMigration", :path => '../'

end

target 'ESMigrationDemo_tvos' do
  use_frameworks!
  pod "ESMigration", :path => '../'

end

target 'ESMigrationDemo_wtchos' do
  use_frameworks!
  pod "ESMigration", :path => '../'

end

target 'ESMigrationDemo_wtchos WatchKit App' do
  use_frameworks!
  pod "ESMigration", :path => '../'

end

target 'ESMigrationDemo_wtchos WatchKit Extension' do
  use_frameworks!
  pod "ESMigration", :path => '../'

end
